spring:
  datasource:
    url: jdbc:mysql://rm-bp164n8m5e78q3zul1o.mysql.rds.aliyuncs.com:3306/mmall?useUnicode=true&characterEncoding=UTF-8
    username: lzx
    password: LZX990601lzx
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/southwind/mapper/xml/*.xml
